"""Git hook generation and installation helpers."""

from __future__ import annotations

from pathlib import Path
from typing import Any


_HOOK_HEADER = """\
#!/bin/bash
# Generated by turnstile - do not edit manually.
# Reinstall with: turnstile hooks install
set -e
"""

_CHECK_SNIPPET = """\
# Check: {description}
turnstile check-completed {process}{state_flag}{param_flags} || {{
  echo "turnstile: {fail_message}"
  exit 1
}}
"""

_PRE_PUSH_GUARD = """\
# Only check when pushing commits (not deletes)
while read local_ref local_sha remote_ref remote_sha; do
  if [ "$local_sha" != "0000000000000000000000000000000000000000" ]; then
{checks}
  fi
done
"""


def generate_check_snippet(
    process: str,
    state: str | None = None,
    parameters: dict[str, str] | None = None,
    description: str | None = None,
) -> str:
    """Generate a single check-completed shell snippet."""
    state_flag = f" --state {state}" if state else ""
    param_flags = ""
    if parameters:
        for k, v in parameters.items():
            param_flags += f" -P {k}={v}"

    desc = description or f"{process} completed"
    if state:
        desc = description or f"{process} reached '{state}'"

    return _CHECK_SNIPPET.format(
        description=desc,
        process=process,
        state_flag=state_flag,
        param_flags=param_flags,
        fail_message=f"Process check failed: {desc}",
    )


def generate_hook(
    hook_type: str,
    checks: list[dict[str, Any]],
) -> str:
    """Generate a complete git hook script.

    Args:
        hook_type: Git hook type (pre-push, pre-commit, etc.).
        checks: List of check configs, each with keys:
            - process: str (required)
            - state: str (optional)
            - parameters: dict (optional)
            - description: str (optional)

    Returns:
        Complete hook script as a string.
    """
    snippets = []
    for check in checks:
        snippet = generate_check_snippet(
            process=check["process"],
            state=check.get("state"),
            parameters=check.get("parameters"),
            description=check.get("description"),
        )
        snippets.append(snippet)

    body = "\n".join(snippets)

    if hook_type == "pre-push":
        # Wrap checks in the pre-push input loop
        indented = "\n".join(
            "    " + line if line.strip() else line
            for snippet in snippets
            for line in snippet.splitlines()
        )
        body = _PRE_PUSH_GUARD.format(checks=indented)

    return _HOOK_HEADER + body


def install_hook(
    hook_type: str,
    script: str,
    project_root: Path,
    force: bool = False,
) -> dict[str, Any]:
    """Install a git hook script.

    Args:
        hook_type: Git hook type (pre-push, pre-commit, etc.).
        script: The hook script content.
        project_root: Project root directory.
        force: Overwrite existing hooks.

    Returns:
        Dict with path, created, and backup info.
    """
    hooks_dir = project_root / ".git" / "hooks"
    if not hooks_dir.exists():
        return {
            "installed": False,
            "error": "No .git/hooks directory found. Is this a git repository?",
        }

    hook_path = hooks_dir / hook_type
    result: dict[str, Any] = {"path": str(hook_path), "hook_type": hook_type}

    if hook_path.exists():
        existing = hook_path.read_text()
        if "Generated by turnstile" in existing:
            # Safe to overwrite our own hooks
            hook_path.write_text(script)
            hook_path.chmod(0o755)
            result["installed"] = True
            result["replaced"] = True
            return result

        if not force:
            result["installed"] = False
            result["error"] = (
                f"Hook '{hook_type}' already exists and was not created "
                f"by turnstile. Use --force to overwrite."
            )
            return result

        # Back up existing hook
        backup_path = hook_path.with_suffix(".backup")
        backup_path.write_text(existing)
        backup_path.chmod(0o755)
        result["backup"] = str(backup_path)

    hook_path.write_text(script)
    hook_path.chmod(0o755)
    result["installed"] = True
    return result


def uninstall_hook(
    hook_type: str,
    project_root: Path,
) -> dict[str, Any]:
    """Remove a turnstile-generated git hook.

    Only removes hooks that were generated by turnstile.
    """
    hooks_dir = project_root / ".git" / "hooks"
    hook_path = hooks_dir / hook_type

    if not hook_path.exists():
        return {"removed": False, "error": f"No '{hook_type}' hook found."}

    content = hook_path.read_text()
    if "Generated by turnstile" not in content:
        return {
            "removed": False,
            "error": f"Hook '{hook_type}' was not created by turnstile.",
        }

    hook_path.unlink()

    # Restore backup if one exists
    backup_path = hook_path.with_suffix(".backup")
    if backup_path.exists():
        backup_path.rename(hook_path)
        return {"removed": True, "restored_backup": True}

    return {"removed": True}
