"""Tests for turnstile_core.hooks (git hook helpers)."""

from pathlib import Path

from turnstile_core.hooks import (
    generate_check_snippet,
    generate_hook,
    install_hook,
    uninstall_hook,
)


class TestGenerateCheckSnippet:
    def test_basic_process(self):
        snippet = generate_check_snippet("feature-deploy")
        assert "turnstile check-completed feature-deploy" in snippet
        assert "feature-deploy completed" in snippet

    def test_with_state(self):
        snippet = generate_check_snippet("feature-deploy", state="merge")
        assert "--state merge" in snippet
        assert "reached 'merge'" in snippet

    def test_with_parameters(self):
        snippet = generate_check_snippet(
            "feature-deploy", parameters={"branch": "main"}
        )
        assert "-P branch=main" in snippet

    def test_with_multiple_parameters(self):
        snippet = generate_check_snippet(
            "feature-deploy",
            parameters={"branch": "main", "env": "prod"},
        )
        assert "-P branch=main" in snippet
        assert "-P env=prod" in snippet

    def test_custom_description(self):
        snippet = generate_check_snippet(
            "feature-deploy", description="deploy process done"
        )
        assert "deploy process done" in snippet

    def test_exit_on_failure(self):
        snippet = generate_check_snippet("release")
        assert "exit 1" in snippet


class TestGenerateHook:
    def test_pre_commit_has_header(self):
        script = generate_hook("pre-commit", [{"process": "release"}])
        assert script.startswith("#!/bin/bash")
        assert "Generated by turnstile" in script

    def test_pre_commit_has_check(self):
        script = generate_hook("pre-commit", [{"process": "release"}])
        assert "turnstile check-completed release" in script

    def test_pre_push_wraps_in_loop(self):
        script = generate_hook("pre-push", [{"process": "release"}])
        assert "while read" in script
        assert "local_ref" in script
        assert "turnstile check-completed release" in script

    def test_pre_push_skips_delete(self):
        script = generate_hook("pre-push", [{"process": "release"}])
        assert "0000000000000000000000000000000000000000" in script

    def test_multiple_checks(self):
        checks = [
            {"process": "feature-deploy", "state": "merge"},
            {"process": "release", "state": "approved"},
        ]
        script = generate_hook("pre-commit", checks)
        assert "feature-deploy" in script
        assert "release" in script
        assert "--state merge" in script
        assert "--state approved" in script

    def test_set_e(self):
        script = generate_hook("pre-commit", [{"process": "release"}])
        assert "set -e" in script


class TestInstallHook:
    def test_install_new_hook(self, tmp_path):
        hooks_dir = tmp_path / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        script = "#!/bin/bash\n# Generated by turnstile\necho test\n"

        result = install_hook("pre-push", script, tmp_path)
        assert result["installed"] is True
        hook = hooks_dir / "pre-push"
        assert hook.exists()
        assert hook.read_text() == script
        # Check executable permission
        assert hook.stat().st_mode & 0o111

    def test_no_git_dir(self, tmp_path):
        result = install_hook("pre-push", "script", tmp_path)
        assert result["installed"] is False
        assert ".git/hooks" in result["error"]

    def test_replace_own_hook(self, tmp_path):
        hooks_dir = tmp_path / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        hook = hooks_dir / "pre-push"
        hook.write_text("#!/bin/bash\n# Generated by turnstile\nold\n")

        new_script = "#!/bin/bash\n# Generated by turnstile\nnew\n"
        result = install_hook("pre-push", new_script, tmp_path)
        assert result["installed"] is True
        assert result.get("replaced") is True
        assert hook.read_text() == new_script

    def test_existing_non_turnstile_hook_blocked(self, tmp_path):
        hooks_dir = tmp_path / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        hook = hooks_dir / "pre-push"
        hook.write_text("#!/bin/bash\necho custom hook\n")

        result = install_hook("pre-push", "new script", tmp_path)
        assert result["installed"] is False
        assert "--force" in result["error"]

    def test_force_backs_up_existing(self, tmp_path):
        hooks_dir = tmp_path / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        hook = hooks_dir / "pre-push"
        hook.write_text("#!/bin/bash\necho custom\n")

        new_script = "#!/bin/bash\n# Generated by turnstile\nnew\n"
        result = install_hook("pre-push", new_script, tmp_path, force=True)
        assert result["installed"] is True
        assert "backup" in result

        backup = hooks_dir / "pre-push.backup"
        assert backup.exists()
        assert backup.read_text() == "#!/bin/bash\necho custom\n"
        assert hook.read_text() == new_script


class TestUninstallHook:
    def test_uninstall_turnstile_hook(self, tmp_path):
        hooks_dir = tmp_path / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        hook = hooks_dir / "pre-push"
        hook.write_text("#!/bin/bash\n# Generated by turnstile\ncheck\n")

        result = uninstall_hook("pre-push", tmp_path)
        assert result["removed"] is True
        assert not hook.exists()

    def test_uninstall_non_turnstile_blocked(self, tmp_path):
        hooks_dir = tmp_path / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        hook = hooks_dir / "pre-push"
        hook.write_text("#!/bin/bash\necho custom\n")

        result = uninstall_hook("pre-push", tmp_path)
        assert result["removed"] is False
        assert "not created by turnstile" in result["error"]
        assert hook.exists()

    def test_uninstall_missing_hook(self, tmp_path):
        hooks_dir = tmp_path / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)

        result = uninstall_hook("pre-push", tmp_path)
        assert result["removed"] is False

    def test_uninstall_restores_backup(self, tmp_path):
        hooks_dir = tmp_path / ".git" / "hooks"
        hooks_dir.mkdir(parents=True)
        hook = hooks_dir / "pre-push"
        hook.write_text("#!/bin/bash\n# Generated by turnstile\ncheck\n")
        backup = hooks_dir / "pre-push.backup"
        backup.write_text("#!/bin/bash\necho original\n")

        result = uninstall_hook("pre-push", tmp_path)
        assert result["removed"] is True
        assert result.get("restored_backup") is True
        assert hook.exists()
        assert hook.read_text() == "#!/bin/bash\necho original\n"
        assert not backup.exists()
